In [ ]:
#QUES.1  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
        #enhance Python's capabilities for numerical operations?
#ANS    Numpy numerical python is a most useful python library which have various inbuilt functions to perform and solve
        #problem.
#Purpose of Numpy:
#It provides other libraries such as Pandas, SciPy, TensorFlow, and scikit-learn, are built on top of NumPy.
#It provides fast and efficiency way to operate on large matrix.
#Multi-dimensional array support: NumPy introduces the concept of the n-dimensional array object, known as ndarray, which can
                                #store large datasets in a structured format. This makes it easy to perform vectorized operations
                                #on entire arrays without needing loops.
#Advantage:
#Fast array operation
#memory effeciency
#supports multi dimentional
#broadcasting


In [ ]:
#QUES2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
        #other?
#ANS.   Both the functions performs same functioning but there is some difference.
#np.mean()
#Computes the arithmetic mean (unweighted).
#Generally faster (less overhead).
#Returns a single value .
#Less overhead for high-speed calculations.

#np.average()
#Computes both simple and weighted averages.
#Can apply weights to the elements of the array.
#Slightly slower due to optional weighting handling.
#More precise if certain elements of the dataset carry different importance.

#when to use np.mean()
#When you need to compute a simple average and do not need to apply weights.
#It is slightly faster and simpler when no weighting is required.

#np.average()
#When you need to calculate a weighted average, which allows certain elements in the array to have more influence on the final result.
#When you need both the average and the sum of the weights (with returned=True).

In [ ]:
#QUES.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
        #arrays.

In [2]:
#First method is slicing
import numpy as np
z=([2,3,4,5])
l=z[::-1]
print(l)

[5, 4, 3, 2]


In [3]:
#second method is np.flip
import numpy as np
z=([2,3,4,5])
l=np.flip(z)
print(l)

[5 4 3 2]


In [7]:
#2-D array
arr=np.array([[1,2,3], [50,40,30], [100,200,300]])
arr_2d=arr[::-1]
print(arr_2d)

[[100 200 300]
 [ 50  40  30]
 [  1   2   3]]


In [8]:
arr=np.array([[1,2,3], [50,40,30], [100,200,300]])
arr_2d=arr[:, ::-1]
print(arr_2d)

[[  3   2   1]
 [ 30  40  50]
 [300 200 100]]


In [11]:
#by np.flip()
arr=np.array([[1,2,3], [50,40,30], [100,200,300]])
arr_2d=np.flip(arr, axis=0)
print(arr_2d)

[[100 200 300]
 [ 50  40  30]
 [  1   2   3]]


In [ ]:
#QUES.4  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
        #in memory management and performance.
#ANS.  It includes int, float, complex dtype known as data type.

In [15]:
import numpy as np
z=np.array([1,2,34])
print(z.dtype)

int32


In [17]:
#data type 
array=np.array([2.2,4.5,6.6])
print(array.dtype)

float64


In [22]:
array=np.array([2+3j, 6+7j])
print(array.dtype)

complex128


In [26]:
array=np.array(['a','i','e'])
print(array.dtype)

<U1


In [ ]:
#importance of data types in memory mgmt
#memory Efficiency
#high speed and accuracy

In [ ]:
#QUES.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
#ANS.  In numpy ndarray means N-Dimensions which have any number of dimensions that contains same datatype.
        #KEY FEATURES:
        #N-Dimensional
        #Homogeneous
        #Efficient Memory Management
        #Vectorized Operations
        #Broadcasting


In [ ]:
#QUES6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
#ANS. Memory Efficiency
    #spped of numerical operations
    #broadcasting
    #Optimized Mathematical Functions
    #Typed and Homogeneous Data
    #provides mathematical operations

In [ ]:
#QUES .7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
        #output.
#ANS. vstack()- allow vertically (row-wise)
                #it should have same number of row.
                #1D array converted into 2D array.
     # hstack()- allow horizontal(column-wise)
                #it should have same number of column.
                #1D array remains in same.
#These functions are used to combine large large into smaller in size by adding row or column.

In [ ]:
#QUES8.  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
        #array dimensions.
#ANS.   fliplr()- flips an array horizontally (left- right)
                #Reverses the column order, keeps row order in 2D array.
                #Not applicable, raises an error in 1D array.
       # flipud()- flips vertically (upside, down, top -bottom)
                    #Reverses the row order, keeps column order in 2D array.
                    #Reverses the order of elements in a 1D array.
#these function used in 2D array.

In [ ]:
#QUES9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#ANS.  The array_split() method in numpy used to split an array into multiple sub array. BUt array_split()
        #can handle uneven splits which divides the array into unequal sizes.

In [ ]:
#QUES 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
        #operations?
#ANS.  Vectorization and broadcasting are two core concepts in NumPy that contribute to its high efficiency for numerical operations. 
        #They enable fast, element-wise operations on arrays without the need for explicit loops, making NumPy highly optimized
        #for large-scale computations.
#Vectorization- It does not require any loop to execute the function rather than it does in single step.
#Broadcasting- It is a mechanism in numpy which allow for operations between arrays and different shapes & size
                #without adding any extra memory allocation or loop.

In [ ]:
#Pratical Questions

In [ ]:
#1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [34]:
import numpy as np
array_random = np.random.randint(1, 101, (3, 3))
print(array_random)

[[47 85 99]
 [19 53 20]
 [65 76  3]]


In [46]:
#interchanging row & column by transpose 
import numpy as np
array=np.array([[20,30,40],
                [55,66,77],
                [99,98,97]])
transpose_array=np.transpose(array)
print(array)
print("\nTranspose array:")
print(transpose_array)

[[20 30 40]
 [55 66 77]
 [99 98 97]]

Transpose array:
[[20 55 99]
 [30 66 98]
 [40 77 97]]


In [ ]:
#2.  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [68]:
import numpy as np
array_1d=np.arange(1,11)
print(array_1d)
array_2x5 = array_1d.reshape(2,5)
print(array_2x5)
array_5x2=array_1d.reshape(5,2)
print("\n array_5x2")
print(array_5x2)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 array_5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [74]:
import numpy as np
array_ran=np.random.rand( 4,4)
print(array_ran)
# Add a border of zeros to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array with Random Floats:")
print(array_4x4)

print("\n6x6 Array with Border of Zeros:")
print(array_6x6)

[[0.0704753  0.7927277  0.7528693  0.809985  ]
 [0.18790335 0.87581719 0.16846741 0.93073534]
 [0.57516594 0.55144358 0.21183129 0.55467485]
 [0.19827511 0.06907435 0.5569846  0.23636426]]
Original 4x4 Array with Random Floats:
[[0.97954373 0.39275364 0.71843943 0.28913426]
 [0.80681038 0.93547929 0.67092143 0.63291794]
 [0.82065204 0.95332937 0.72328797 0.73513158]
 [0.69730771 0.87939288 0.6984049  0.22793709]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.97954373 0.39275364 0.71843943 0.28913426 0.        ]
 [0.         0.80681038 0.93547929 0.67092143 0.63291794 0.        ]
 [0.         0.82065204 0.95332937 0.72328797 0.73513158 0.        ]
 [0.         0.69730771 0.87939288 0.6984049  0.22793709 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [84]:
import numpy as np
array = np.arange(10 , 65, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#5. . Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
        #(uppercase, lowercase, title case, etc.) to each element.

In [87]:
import numpy as np
array=np.array(['python', 'numpy', 'pandas'])
uppercase=np.char.upper(array)
lowercase=np.char.lower(array)
titlecase=np.char.title(array)
print(array)
print(uppercase)
print(lowercase)
print(titlecase)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [ ]:
#6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [91]:
import numpy as np
x=np.array(['vini', 'aditya', 'bruzi'])
l=np.char.join('   ', x)
print(x)
print(l)

['vini' 'aditya' 'bruzi']
['v   i   n   i' 'a   d   i   t   y   a' 'b   r   u   z   i']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [99]:
import numpy as np
array1= np.array([[12,13,76],
                  [32,56,54]])
array2=np.array([[87,90,65],
                [32,87,99]])
addition=np.add(array1, array2)
subtraction=np.subtract(array1, array2)
multiplication=np.multiply(array1, array2)
division=np.divide(array1, array2)
print(array1)
print(array2)
print('\n addition')
print(addition)
print("\n subtraction")
print(subtraction)
print("\n division")
print(division)

[[12 13 76]
 [32 56 54]]
[[87 90 65]
 [32 87 99]]

 addition
[[ 99 103 141]
 [ 64 143 153]]

 subtraction
[[-75 -77  11]
 [  0 -31 -45]]

 division
[[0.13793103 0.14444444 1.16923077]
 [1.         0.64367816 0.54545455]]


In [ ]:
#8.  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [100]:
import numpy as np
identity =np.eye(5)
diagonal=np.diag(identity)

print(identity)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [ ]:
#9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
    #this array.

In [102]:
import numpy as np
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Array of Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Random Array of Integers:
[220 676 478 251 543 208 531 967 299 173 948 644 823 794 700 480  67 212
  20 345 901 448 626 504 792 522 754 147 406  21 336 820 762 542 120 861
 667 858 337 546 146 877 518 379 929 368 721 430  35 427  57 938  66 266
 462 317 479 102  65 321 497 264 638  11 272 982 401 811 520 492 739 372
 359 281 597 102 912 771 505 116  94 998 724 556 375 366 495 592 256 717
  24 679 176 750 590  11 957 965  91 230]

Prime Numbers in the Array:
[251, 967, 173, 823, 67, 337, 877, 379, 929, 317, 479, 11, 401, 811, 739, 359, 281, 11]


In [ ]:
#10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
    #averages.

In [103]:
import numpy as np
daily_temperatures = np.random.randint(15, 36, 30)
weeks_temperatures = daily_temperatures[:28].reshape(4, 7)
extra_days = daily_temperatures[28:]

weekly_averages = np.mean(weeks_temperatures, axis=1)
extra_days_average = np.mean(extra_days)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)

print("\nAverage for the last 2 days:")
print(extra_days_average)


Daily Temperatures for the Month:
[31 21 29 28 24 27 23 22 27 20 29 17 34 31 26 27 19 27 23 17 35 18 26 33
 22 32 30 18 28 35]

Weekly Averages:
[26.14285714 25.71428571 24.85714286 25.57142857]

Average for the last 2 days:
31.5
